// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddUser(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckAndSetupPaths():Promise<void>;

export function CheckAssets():Promise<boolean>;

export function DeleteUser(arg1:string):Promise<void>;

export function DownloadAssets():Promise<void>;

export function GetLicenseText():Promise<string>;

export function GetServerStatus():Promise<Record<string, any>>;

export function GetTTSConfig():Promise<main.ServerTTSConfig>;

export function GetUsers():Promise<Array<Record<string, string>>>;

export function GetVoiceStyles():Promise<Array<string>>;

export function SetEnableTTS(arg1:boolean):Promise<void>;

export function SetLLMEndpoint(arg1:string):Promise<void>;

export function SetPort(arg1:string):Promise<void>;

export function SetTTSConfig(arg1:string,arg2:number):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer():Promise<void>;
