// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddUser'](arg1, arg2, arg3);
}

export function CheckAndSetupPaths() {
  return window['go']['main']['App']['CheckAndSetupPaths']();
}

export function CheckAssets() {
  return window['go']['main']['App']['CheckAssets']();
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DownloadAssets() {
  return window['go']['main']['App']['DownloadAssets']();
}

export function GetLicenseText() {
  return window['go']['main']['App']['GetLicenseText']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetTTSConfig() {
  return window['go']['main']['App']['GetTTSConfig']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetVoiceStyles() {
  return window['go']['main']['App']['GetVoiceStyles']();
}

export function SetEnableTTS(arg1) {
  return window['go']['main']['App']['SetEnableTTS'](arg1);
}

export function SetLLMEndpoint(arg1) {
  return window['go']['main']['App']['SetLLMEndpoint'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function SetTTSConfig(arg1, arg2) {
  return window['go']['main']['App']['SetTTSConfig'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
