// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddUser(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckAndSetupPaths():Promise<void>;

export function CheckAssets():Promise<boolean>;

export function CheckHealth():Promise<main.HealthCheckResult>;

export function DeleteUser(arg1:string):Promise<void>;

export function DownloadAssets():Promise<void>;

export function GetAutoStartServer():Promise<boolean>;

export function GetLicenseText():Promise<string>;

export function GetMinimizeToTray():Promise<boolean>;

export function GetServerStatus():Promise<Record<string, any>>;

export function GetStartOnBoot():Promise<boolean>;

export function GetSystemPrompts():Promise<Array<main.SystemPrompt>>;

export function GetTTSConfig():Promise<main.ServerTTSConfig>;

export function GetTTSDictionary(arg1:string):Promise<Record<string, string>>;

export function GetUsers():Promise<Array<Record<string, string>>>;

export function GetVoiceStyles():Promise<Array<string>>;

export function SetAutoStartServer(arg1:boolean):Promise<void>;

export function SetEnableTTS(arg1:boolean):Promise<void>;

export function SetLLMApiToken(arg1:string):Promise<void>;

export function SetLLMEndpoint(arg1:string):Promise<void>;

export function SetLLMMode(arg1:string):Promise<void>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function SetPort(arg1:string):Promise<void>;

export function SetStartOnBoot(arg1:boolean):Promise<void>;

export function SetTTSConfig(arg1:string,arg2:number):Promise<void>;

export function SetTTSThreads(arg1:number):Promise<void>;

export function ShowAbout():Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StartServerWithCurrentConfig():Promise<void>;

export function StopServer():Promise<void>;
