// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddUser'](arg1, arg2, arg3);
}

export function CheckAndSetupPaths() {
  return window['go']['main']['App']['CheckAndSetupPaths']();
}

export function CheckAssets() {
  return window['go']['main']['App']['CheckAssets']();
}

export function CheckHealth() {
  return window['go']['main']['App']['CheckHealth']();
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DownloadAssets() {
  return window['go']['main']['App']['DownloadAssets']();
}

export function GetAutoStartServer() {
  return window['go']['main']['App']['GetAutoStartServer']();
}

export function GetLicenseText() {
  return window['go']['main']['App']['GetLicenseText']();
}

export function GetMinimizeToTray() {
  return window['go']['main']['App']['GetMinimizeToTray']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetStartOnBoot() {
  return window['go']['main']['App']['GetStartOnBoot']();
}

export function GetSystemPrompts() {
  return window['go']['main']['App']['GetSystemPrompts']();
}

export function GetTTSConfig() {
  return window['go']['main']['App']['GetTTSConfig']();
}

export function GetTTSDictionary(arg1) {
  return window['go']['main']['App']['GetTTSDictionary'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetVoiceStyles() {
  return window['go']['main']['App']['GetVoiceStyles']();
}

export function SetAutoStartServer(arg1) {
  return window['go']['main']['App']['SetAutoStartServer'](arg1);
}

export function SetEnableTTS(arg1) {
  return window['go']['main']['App']['SetEnableTTS'](arg1);
}

export function SetLLMApiToken(arg1) {
  return window['go']['main']['App']['SetLLMApiToken'](arg1);
}

export function SetLLMEndpoint(arg1) {
  return window['go']['main']['App']['SetLLMEndpoint'](arg1);
}

export function SetLLMMode(arg1) {
  return window['go']['main']['App']['SetLLMMode'](arg1);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['main']['App']['SetMinimizeToTray'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function SetStartOnBoot(arg1) {
  return window['go']['main']['App']['SetStartOnBoot'](arg1);
}

export function SetTTSConfig(arg1, arg2) {
  return window['go']['main']['App']['SetTTSConfig'](arg1, arg2);
}

export function SetTTSThreads(arg1) {
  return window['go']['main']['App']['SetTTSThreads'](arg1);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StartServerWithCurrentConfig() {
  return window['go']['main']['App']['StartServerWithCurrentConfig']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
